### PR TITLE
Improve FPF error message callbacks with error object arguments and XML/HTML return values

### PR DESCRIPTION
**Pull request by thomasbachem**

### CODE REVIEW

**Comment by graste** [comment]
Good change. Do you provide the callback dynamically? I thought about changing the order of the ```is_string``` and ```is_callable``` calls to be able to write something like the following in the ```global_filters.xml``` FPF part:

```xml
<ae:parameter name="markup">Your\Custom\ErrorRenderer::getErrorDomElement</ae:parameter>
```

**Comment by thomasbachem** [comment]
@graste Great idea, I'm providing it dynamically right now, but I think we should support your proposal as well.

@ddelbondio Can you merge this one? Then @graste can add his improvement with another pull req. Or can he add something to this one as well?

**Comment by graste** [comment]
Would be easier when you change it in your branch I guess.

**Comment by thomasbachem** [comment]
You're invited to provide a patch then ;)

**Pull request closed without merging**
