### PR TITLE
AgaviHttpRedirectRoutingCallback: Add support to modify parts of the request URL

### PR DESCRIPTION
**Pull request by thomasbachem**
In addition to supply a full URL or route to the redirect routing callback, one can now also change certain URL parts (specifically 'scheme', 'host', 'port', 'user', 'pass', 'path', 'query' and 'fragment') of the current request URL.

### CODE REVIEW

**Comment by ddelbondio** [comment]
Can you move buildUrl to AgaviToolkit please?

**Comment by thomasbachem** [comment]
Done.

**Comment by dzuelke** [comment]
Rebase/squash that please.

**Comment by thomasbachem** [comment]
I awaited your comment on this, @dzuelke. I too think it should not go into AgaviToolkit.

**Comment by thomasbachem** [comment]
Rebase done, the method is in `AgaviHttpRedirectRoutingCallback` again.

**Comment by thomasbachem** [comment]
@ddelbondio We should avoid putting methods into `AgaviToolkit` whenever possible, as these classes tend to grow infinitely otherwise. And keeping it in `AgaviHttpRedirectRoutingCallback` lets us keep it protected instead of public. Or do you have another use case inside of Agavi for this method?

**Comment by dzuelke** [comment]
I meant something like `git rebase --interactive upstream/http-redirect-routing-callback~2 http-redirect-routing-callback` then `f`/`s` the second commit to merge it with the first.

**Comment by thomasbachem** [comment]
Ok, so what are you proposing to do now ;)?

**Comment by ddelbondio** [comment]
I see two ways of approaching the issue here, either we make the method private, which gives us the possibility to move it to AgaviToolkit later without a BC break, or we put it into AgaviToolkit right now.
While I agree with your bloat remark, I still prefer putting it into AgaviToolkit, since it's a generally useful function. (Strictly speaking it should really be a standalone function, but that's out of scope due to the missing autoload support for these)

**Comment by thomasbachem** [comment]
I'm strongly against private methods, as they prevent any way of extending/fixing things in userland. I think it's obvious to users that they shouldn't rely on using an internal protected method like this, and even if they do, we could still keep an alias that wraps `AgaviToolkit::buildUrl()` in `AgaviHttpRedirectRoutingCallback` if we decide to move it there later on.

**Comment by dzuelke** [comment]
I just wanted both commits squashed into one. For simple things like this it's better to do that instead of having multiple individual commits that make history harder to read. For longer lasting, more complex, or collaborative changes, many commits and a non fast forwarded merge are better.

**Comment by thomasbachem** [comment]
Ok, I moved the method to `AgaviToolkit` now, but squashed it into a single commit.

**Pull request closed without merging**
